name: channel_mock
description: A package to help mock communications channels in Flutter to make unit testing and mocking flutter plugins easier
homepage: https://github.com/flutter-institute/channel_mock
version: 2.0.1

environment:
  sdk: ">=2.17.6 <4.0.0"

dependencies:
  collection: ^1.17.2
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies:
  firebase_auth: ^4.9.0
